import { routes } from "@/config/routes/routes";
import CurrencyView from "@/sections/currency";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";

export default async function page() {
  const user = await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();
  await currentUser();

  if (!user) {
    redirect(routes.signIn);
  }
  return <CurrencyView firstName={user.firstName || ''} />;
}
